# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djmoney_rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ratesource',
            name='base_currency',
            field=models.CharField(max_length=10),
        ),
    ]
